networks:
  docker-compose-exercise:
    driver: bridge

services:
  database:
    image: koenkk/docker-compose-exercise-database
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    networks:
      - docker-compose-exercise

  webapp:
    image: koenkk/docker-compose-exercise-webapp
    ports:
      - "8080:80"
    networks:
      - docker-compose-exercise